apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "05 01 20 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      backoffLimit: 0
      template:
        spec:
          containers:
            - image: postgres:16.4-alpine
              name: db
              volumeMounts:
                - name: backup-volume
                  mountPath: /tmp/backup
              resources:
                limits:
                  memory: 396Mi
              command: ["sh", "-c", "pg_dumpall -h db -c --if-exists > /tmp/backup/backup.sql"]
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: nextcloud-db-password
                  name: nextcloud-db
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: nextcloud-db-user
                  name: nextcloud-db
          volumes:
            - name: backup-volume
              hostPath:
                path: /mnt/data/nextcloud
                type: Directory
          restartPolicy: Never
