apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.templates.app.name }}-db
  namespace: {{ .Values.templates.app.namespace }}
  labels:
    app: {{ .Values.templates.app.name }}-db
spec:
  ports:
    - port: {{ .Values.database.port }}
      name: psql
  clusterIP: None
  selector:
    app: {{ .Values.templates.app.name }}-db
