apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: {{ .Values.templates.app.namespace }}
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: nextcloud
