# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directories: 
      - "/charts/*"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"