# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/charts/argocd"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"
  - directory: "/charts/cert-manager"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"
  - directory: "/charts/nfty"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"
  - directory: "/charts/nextcloud"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"
  - directory: "/charts/paperless"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"
  - directory: "/charts/traefik"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Berlin"
