# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/charts/nextcloud"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "20:30"
      timezone: "Europe/Berlin"