repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        exclude: |
          (?x)(
              ^charts/[a-zA-Z-]*/templates/|
              ^.templates
          )


    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
  - id: helmlint
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.19.2
  hooks:
    - id: gitleaks
