apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.templates.app.name }}
  namespace: {{ .Values.templates.app.name }}
spec:
  storageClassName: microk8s-hostpath
  volumeName: {{ .Values.templates.app.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.templates.pv.capacity }}
