apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "05 02 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            storage: "host"
          volumes:
            - name: paperless-volume
              hostPath:
                path: /mnt/data/paperless
                type: DirectoryOrCreate
          containers:
            - image: ghcr.io/paperless-ngx/paperless-ngx:2.15.2
              name: backup
              volumeMounts:
                - name: paperless-volume
                  mountPath: "/usr/src/paperless/data"
                  subPath: "data"
                - name: paperless-volume
                  mountPath: "/usr/src/paperless/media"
                  subPath: "media"
                - name: paperless-volume
                  mountPath: "/usr/src/paperless/export"
                  subPath: "export"
                - name: paperless-volume
                  mountPath: "/usr/src/paperless/consume"
                  subPath: "consume"
              env:
                - name: TZ
                  value: Europe/Berlin
                - name: PAPERLESS_PORT
                  value: "8000"
                - name: PAPERLESS_REDIS
                  value: redis://redis:6379
                - name: PAPERLESS_DBHOST
                  value: "db"
                - name: PAPERLESS_ENABLE_UPDATE_CHECK
                  value: "true"
                - name: USERMAP_UID
                  value: "1000"
                - name: USERMAP_GID
                  value: "1000"
                - name: PAPERLESS_OCR_LANGUAGES
                  value: "deu eng"
                - name: "PAPERLESS_TIME_ZONE"
                  value: "Europe/Berlin"
                - name: PAPERLESS_OCR_LANGUAGE
                  value: "deu"
                - name: PAPERLESS_FILENAME_FORMAT
                  value: "{created_year}/{correspondent}/{title}"
                - name: PAPERLESS_DBPASS
                  valueFrom:
                    secretKeyRef:
                      key: paperless-db-password
                      name: paperless-db
                - name: PAPERLESS_DBUSER
                  valueFrom:
                    secretKeyRef:
                      key: paperless-db-user
                      name: paperless-db
                - name: PAPERLESS_DBNAME
                  valueFrom:
                    secretKeyRef:
                      key: paperless-db
                      name: paperless-db
                - name: PAPERLESS_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: paperless-admin-user
                      name: paperless-db
                - name: PAPERLESS_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: paperless-admin-password
                      name: paperless-db
                - name: PAPERLESS_ADMIN_MAIL
                  valueFrom:
                    secretKeyRef:
                      key: paperless-admin-mail
                      name: paperless-db
                - name: PAPERLESS_URL
                  value: https://paperless.matthiasstein.net
              command:
                [
                  "sh",
                  "-c",
                  "document_exporter /usr/src/paperless/export --compare-checksums --no-progress-bar",
                ]
          restartPolicy: Never
