apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-db-init-script
  namespace: paperless
data:
  init_script.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

      CREATE DATABASE $PAPERLESS_DB OWNER $POSTGRES_USER TEMPLATE template0 ENCODING 'UTF8';
      GRANT ALL PRIVILEGES ON DATABASE $PAPERLESS_DB TO $POSTGRES_USER;
      GRANT ALL PRIVILEGES ON SCHEMA public TO $POSTGRES_USER;

    EOSQL
