apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "05 02 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      backoffLimit: 0
      template:
        spec:
          containers:
            - image: postgres:17.2-alpine
              name: db
              volumeMounts:
                - name: backup-volume
                  mountPath: /tmp/backup
              resources:
                limits:
                  memory: 396Mi
              command: ["sh", "-c", "pg_dumpall -h db --database=$PAPERLESS_DB -c --if-exists > /tmp/backup/backup.sql"]
              env:
                - name: PAPERLESS_DB
                  valueFrom:
                    secretKeyRef:
                      key: paperless-db
                      name: paperless-db
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: paperless-db-password
                      name: paperless-db
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: paperless-db-user
                      name: paperless-db
          volumes:
            - name: backup-volume
              hostPath:
                path: /mnt/data/paperless
                type: Directory
          restartPolicy: Never
