apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
  labels:
    app: paperless
spec:
  ports:
    - port: 8000
      name: http
  clusterIP: None
  selector:
    app: paperless
