templates:
  app:
    name: traefik
    namespace: traefik
  certificate:
    install: false
    issuer: letsencrypt-staging # letsencrypt-production
    dns_names:
      - traefik.matthiasstein.net
  http_redirect:
    enable: false
  dashboard_hostname: traefik.matthiasstein.net
  dashboard_auth: true

traefik:
  env:
    - name: TZ # set timezone
      value: Europe/Berlin
  image:
    registry: docker.io
    repository: traefik
    tag: 3.3.5
  # Removing to allow IP setting
  ports:
    # Configure your entrypoints here...
    web:
      # (optional) Permanent Redirect to HTTPS
      redirectTo.port: websecure
    websecure:
      enabled: true
      # (optional) Set a Default CertResolver
      # certResolver: cloudflare
  globalArguments:
    - "--global.checknewversion"
    - "--serversTransport.insecureSkipVerify=true"
  service:
    spec:
      externalTrafficPolicy: Local
  ingressRoute:
    dashboard:
      enabled: true
  providers:
    #kubernetesCRD:
    #  enabled: true
    kubernetesIngress:
      enabled: true
      # IP used for Kubernetes Ingress endpoints
      publishedService:
        enabled: true
        # Published Kubernetes Service to copy status from. Format: namespace/servicename
        # By default this Traefik service
        # pathOverride: ""
  # Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
  ingressClass:
    enabled: true
    isDefaultClass: true
  rbac:
    enabled: true
  logs:
    # Configure log settings here...
    general:
      level: INFO

  additionalArguments:
    - "--providers.kubernetesingress.allowemptyservices=true"
    - "--providers.kubernetesingress.allowexternalnameservices=true"
    - "--providers.kubernetescrd.allowemptyservices=true"
    - "--providers.kubernetescrd.allowexternalnameservices=true"
  persistence:
    enabled: true
    path: /certs
    size: 128Mi
