{{- if .Values.templates.dashboard_hostname }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tls-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.templates.dashboard_hostname }}`)
      kind: Rule
      {{- if .Values.templates.dashboard_auth }}
      middlewares:
      - name: auth
      - name: local-ipallowlist
      {{- end }}
      services:
      - name: api@internal
        kind: TraefikService
  tls:
      store:
          name: default
{{- end }}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-http-redirect
spec:
  entryPoints:
  - web
  routes:
  - match: HostRegexp(`{host:.+}`)
    kind: Rule
    services:
    - name: noop@internal
      kind: TraefikService
    middlewares:
        - name: http-redirect
