apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: onlyoffice-headers
spec:
  headers:
    accessControlAllowOriginList: 
      - "*"
    customRequestHeaders:
      X-Forwarded-Proto: "https"