apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-headers
spec:
  headers:
    referrerPolicy: no-referrer
    SSLRedirect: true
    STSSeconds: 315360000
    browserXSSFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    STSIncludeSubdomains: true
    STSPreload: true
    customFrameOptionsValue: SAMEORIGIN