apiVersion: traefik.io/v1
kind: Middleware
metadata:
  name: nextcloud-headers
spec:
  headers:
    referrerPolicy: no-referrer
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    customFrameOptionsValue: SAMEORIGIN