kind: Service
apiVersion: v1
metadata:
  name: openproject
spec:
  type: ExternalName
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  externalName: 192.168.10.227
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openproject
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openproject.matthiasstein.net`)
      kind: Rule
      priority: 1
      services:
        - kind: Service
          name: openproject
          port: 8080
