apiVersion: traefik.io/v1alpha1
kind: Service
metadata:
  name: openproject
spec:
  loadBalancer:
    servers:
      - url: "https://192.168.10.227:8080"
    passHostHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openproject
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openproject.matthiasstein.net`)
      kind: Rule
      priority: 5
      services:
        - kind: Service
          name: openproject
          port: 8080
