{{- if .Values.templates.default_cert }}
apiVersion: traefik.io/v1
kind: TLSStore
metadata:
  name: default
  namespace: traefik


spec:
  defaultCertificate:
    secretName:  {{ .Values.templates.default_cert }}
{{- end }}