{{- if .Values.templates.certificate.install }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.templates.app.name }}
spec:
  secretName: {{ .Values.templates.app.name }}-cert
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  {{- range .Values.templates.certificate.dns_names }}
  - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ .Values.templates.certificate.issuer }}
    kind: ClusterIssuer
{{- end }}
