apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.templates.app.name }}
  namespace: {{ .Values.templates.app.namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.templates.app.name }}
  capacity:
    storage: {{ .Values.templates.pv.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.templates.pv.base_path }}/{{ .Values.templates.app.name }}"
    type: DirectoryOrCreate
