apiVersion: v1
kind: Service
metadata:
  name: teddycloud
  namespace: teddycloud
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.29
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: webinterface
      port: 8443
      targetPort: 8443
  selector:
    app: teddycloud
