apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.templates.pv.storageClass }}
  resources:
    requests:
      storage: {{ .Values.templates.pv.capacity }}
