apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.templates.app.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.templates.app.name }}
  resources:
    requests:
      storage: {{ .Values.templates.pv.capacity }}