apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onlyoffice.fullname" . }}
  labels:
    app: {{ include "onlyoffice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "onlyoffice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onlyoffice.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: JWT_ENABLED
              value: "true"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-jwt-secret
                  key: secret
          volumeMounts:
            {{- range $key, $value := .Values.persistence.volumes }}
            {{- if $value.enabled }}
            - name: onlyoffice-{{ $key }}
              mountPath: {{ $value.mountPath }}
            {{- end }}
            {{- end }}
            - name: onlyoffice-license
              mountPath: {{ .Values.license.mountPath }}/{{ .Values.license.licenseFileName }}
              subPath: {{ .Values.license.licenseFileName }}
      volumes:
        {{- range $key, $value := .Values.persistence.volumes }}
        {{- if $value.enabled }}
        - name: onlyoffice-{{ $key }}
          hostPath:
            path: {{ $value.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
        {{- end }}
        - name: onlyoffice-license
          secret:
            secretName: {{ .Values.license.secretName }}