{{- range $key, $value := .Values.persistence.volumes }}
{{- if $value.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onlyoffice-{{ $key }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.size }}
  storageClassName: {{ $value.storageClass | quote }}
---
{{- end }}
{{- end }}