templates:
  app:
    name: nextcloud
    namespace: nextcloud
  certificate:
    install: false
    # issuer: letsencrypt-staging
    issuer: letsencrypt-production
    dns_names:
      - nextcloud.matthiasstein.net
  ingress:
    url: nextcloud.matthiasstein.net
    service: nextcloud
    port: 80
  pv:
    base_path: "/mnt/data"
    capacity: 10Gi

database:
  port: 5432
  image: postgres:17.4-alpine
  mountPath: /var/lib/postgresql/data
  backupImportPath: /tmp/backup
  backupFile: backup.sql
  volumes:
    path: /mnt/data/nextcloud/postgres
    backupImportPath: /mnt/data/nextcloud/backup

nextcloud:
  image:
    repository: nextcloud
    tag: 31.0.4
    pullPolicy: IfNotPresent

  volumeMounts:
    - mountPath: "/var/www/html"
      name: nextcloud-config
    - mountPath: "/var/www/html/data"
      name: nextcloud-data
    - mountPath: "/var/data/paperless/consume"
      name: paperless-volume

  volumes:
    - name: nextcloud-config
      hostPath:
        path: /mnt/data/nextcloud/config
        type: DirectoryOrCreate
    - name: nextcloud-data
      hostPath:
        path: /mnt/data/nextcloud/data
        type: DirectoryOrCreate
    - name: paperless-volume
      hostPath:
        path: /mnt/data/paperless/consume
        type: DirectoryOrCreate
  resources:
    limits:
      memory: 1024Mi
      # cpu: 1000m

  # Number of replicas to be deployed
  replicaCount: 1
  revisionHistoryLimit: 3
  env:
    - name: NEXTCLOUD_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: nextcloud-admin-username
    - name: NEXTCLOUD_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: nextcloud-admin-password
    - name: NEXTCLOUD_TRUSTED_DOMAINS
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: trusted-domains
    - name: TRUSTED_PROXIES
      value: "10.0.0.0/8"
    - name: SMTP_NAME
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: smtp_name
    - name: SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: smtp_host
    - name: SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: smtp_port
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: smtp_password
    - name: MAIL_FROM_ADDRESS
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: mail_from_address
    - name: MAIL_DOMAIN
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: mail_domain
    - name: SMTP_SECURE
      valueFrom:
        secretKeyRef:
          name: nextcloud
          key: smtp_secure
    - name: POSTGRES_HOST
      valueFrom:
        secretKeyRef:
          name: nextcloud-db
          key: nextcloud-db-host
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: nextcloud-db
          key: nextcloud-db
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: nextcloud-db
          key: nextcloud-db-user
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud-db
          key: nextcloud-db-password
    - name: REDIS_HOST
      valueFrom:
        secretKeyRef:
          name: nextcloud-redis
          key: nextcloud-redis-host
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    successThreshold: 1
