apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd
    namespace: argocd
spec:
    destination:
        namespace: argocd
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/onehinny/homelab.git
        path: charts/argocd
        targetRevision: main
        helm:
            valueFiles:
                - values.yaml
    syncPolicy:
        syncOptions:
          - CreateNamespace=true
