apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: cert-manager
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        namespace: cert-manager
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/onehinny/homelab.git
        path: charts/cert-manager
        targetRevision: main
        helm:
            valueFiles:
                - values.yaml
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
          - CreateNamespace=true
