apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: homeassistant
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        namespace: homeassistant
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/onehinny/homelab.git
        path: charts/homeassistant
        targetRevision: longhorn
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
          - CreateNamespace=true
