apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mqtt
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        namespace: mqtt
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/onehinny/homelab.git
        path: charts/mqtt
        targetRevision: main
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
          - CreateNamespace=true
