apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nextcloud
    namespace: argocd
spec:
    destination:
        namespace: nextcloud
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/onehinny/homelab.git
        path: apps/nextcloud
        targetRevision: test
        helm:
            valueFiles:
                - values.yaml
    syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
