apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: onlyoffice
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        namespace: onlyoffice
        server: kube02
    project: default
    source:
        repoURL: https://github.com/onehinny/homelab.git
        path: charts/onlyoffice
        targetRevision: main
        helm:
            valueFiles:
                - values.yaml
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
          - CreateNamespace=true
