apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teddycloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teddycloud
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/onehinny/homelab.git
    path: charts/teddycloud
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
