apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: traefik
    namespace: argocd
spec:
    destination:
        namespace: traefik
        server: https://kubernetes.default.svc
    project: default
    source:
        path: traefik
        targetRevision: test
        helm:
            valueFiles:
                - values.yaml
        repoURL: https://github.com/chris-sanders/argocd.git
    syncPolicy:
        automated:
            prune: true
        syncOptions:
          - CreateNamespace=true
