cert-manager:
    global:
      leaderElection:
        # Override the namespace used to store the ConfigMap for leader election
        namespace: "cert-manager"
    installCRDs: true
    extraArgs: 
        - --cluster-resource-namespace=cert-manager
        - --enable-certificate-owner-ref=true
    image:
        repository: quay.io/jetstack/cert-manager-controller
        tag: v1.12.2
    webhook:
        image:
            repository: quay.io/jetstack/cert-manager-webhook
            tag: v1.12.2
    cainjector:
        image:
            repository: quay.io/jetstack/cert-manager-cainjector
            tag: v1.12.2
templates:
    letsencrypt:
        production: true
        staging: true
        selfSigned: false
        email: cloud@matthiasstein.net
        acme_host: 'dns.example.com'
    cloudflare:
        email: clould@matthiasstein.net
    secrets: ''
