cert-manager:
    global:
      leaderElection:
        # Override the namespace used to store the ConfigMap for leader election
        namespace: "cert-manager"
    installCRDs: true
    extraArgs: 
        - --cluster-resource-namespace=cert-manager
        - --enable-certificate-owner-ref=true
templates:
    letsencrypt:
        production: false
        staging: false
        selfSigned: false
        email: cloud@matthiasstein.net
        acme_host: 'dns.example.com'
    cloudflare:
        email: clould@matthiasstein.net
    secrets: ''
