argo-cd:
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.1.8
  controller:
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.1.8
  dex:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.44.0
    enabled: false
  redis:
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 8.2.2-alpine
  server:
    extraArgs:
      # - --insecure
    config:
      repositories: |
        - type: git
          name: homelab
          url: https://github.com/onehinny/homelab.git

templates:
  app:
    name: argocd
    namespace: argocd
  certificate:
    install: false
    # issuer: letsencrypt-staging
    issuer: letsencrypt-production
    dns_names:
      - argocd.matthiasstein.net
  ingress:
    url: argocd.matthiasstein.net
    service: argocd-server
    port: 443
