argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      # - --insecure
    config:
      repositories: |
        - type: git
          name: homelab
          url: https://github.com/onehinny/homelab.git

templates:
  app:
    name: argocd
    namespace: argocd
  certificate: 
    install: true
    # issuer: letsencrypt-staging
    issuer: letsencrypt-production
    dns_names: 
      - argocd.matthiasstein.net
  ingress:
    url: argocd.matthiasstein.net
    service: argocd-server
    prot: 443
